### ISSUE TITLE
undefined reference to 'gst_player_get_instance_private'

### ISSUE THREAD

**Issue by rahmanih** [sdroege/gst-player#104]
trying to build the current tree I'm getting the following error:

CCLD   gst-play
../lib/gst/player/.libs/libgstplayer-0.0.so: **undefined reference to `gst_player_get_instance_private'**
collect2: error: ld returned 1 exit status
make[2]: *** [gst-play] Error 1

I can't find the _gst_player_get_instance_private()_ implemented anywhere in the code.

is this a konwn issue or am I missing something?

regards

**Comment by sdroege** [comment]
That's because you use an older GLib version. I'll have to check which one added this feature

**Comment by rahmanih** [comment]
I'm using the GLib 2.34.1

**Comment by sdroege** [comment]
2.38.0 introduced it. I'll increase the requirement. Thanks for reporting!

**Comment by rahmanih** [comment]
is there any alternative for older GLib?, I'm working on embedded system and it is diffcult to update the 
GLib package.

regards

**Comment by sdroege** [comment]
GLib 2.34 is from 2012, you should consider updating your system in general. You will also need a newer GStreamer version than the one from 2012... and there are quite a few bugs you will observe in GStreamer if you run it with such an old GLib version.

**Comment by rahmanih** [comment]
O.K got it!
thanks.

**Comment by sdroege** [comment]
Sorry if that causes any inconveniences to you. What platform are you using btw, that is shipping such an old GLib?
