### ISSUE TITLE
Add rate control to simple gst-player API

### ISSUE THREAD

**Issue by david-a-wheeler** [sdroege/gst-player#113]
The recent LWN article about the gst-player API <https://lwn.net/Articles/660528> says that "gst-player offers four operations: play, pause, stop, and seek (to a specified time in the media)".  Simple is good, but for me there's another operation that's a bare minimum: speed control (at least for audio).  I *always* listen to recorded speech at 2x or more where possible; it's given me months of my life back (and I strongly recommend it).  Please add that to the short list of operations supported by the simple API, thanks!

**Comment by sdroege** [comment]
You can already change the playback rate, there's API for that. What does not exist yet is an option to keep the audio pitch (you don't always want to hear chipmunk voices). That part is handled in https://github.com/sdroege/gst-player/issues/97 and relatively trivial to add. I guess I'll do that as a next step then, already two people asked for it ;)

**Comment by sdroege** [comment]
This is implemented now
