### ISSUE TITLE
media info

### ISSUE THREAD

**Issue by codomania** [sdroege/gst-player#12]
Hi Sebastian,
I have added new API to query the current media information using gst tags. I just did two commits in my forked tree today:

[https://github.com/codomania?tab=activity]
 
a88d429 Add new keyboard key 'i' to query the current stream information
66cdc68 add new api gst_player_get_stream_info () to obtain the current stream information

The first commits adds api and second commit update gst-play keyboard handler to use this api for querying the media information (when user press i).  If you are okay with the approach then I can continue and add the other tags (e.g audio, etc). If you have any other approach in mind then do let me know. 

Thanks
Brijesh 

The output look like this:

Title: 300: Rise of an Empire - Trailer 2
Artist: Warner Bros.
Album: (null)
Date: 1/1/2014
Genre: Trailer
Tracks: 0/0
Copyright: (null)
License: (null)
Comment: (null)
video
 codec: H.264
 resolution: 1920 x 1088
 framerate: 23.98

**Comment by sdroege** [comment]
Thanks, also see https://github.com/sdroege/gst-player/pull/9 for a previous implementation of this and my thoughts on how it should look like. Overall I would like to have some GstDiscoverer-style data structures with all the media information, not only with the currently selected audio/video/text streams but also with the possibility of getting information about the non-selected ones.

That would allow an application to understand e.g. which other audio languages are available, and then select one appropriately.


Also there should be a signal for whenever the stream information are changing.

**Comment by codomania** [comment]
Thanks, I will take a look at both #9 and GstDiscoverer-style.

**Comment by codomania** [comment]
Thanks for pointing out gst-discoverer, i did not knew this before and it was good read for me.
I just pushed two commits on my dev branch with draft implementation:

https://github.com/codomania/gst-player/commits/dev
33daff4d59acfac67e5bc1cf6be8a8c5eb334f66
bf02352623c46df674e3d7f8b408142750411884

Please let me know if I am on the right track. If you are okay with the approach then I can continue and add the missing audio and subtitle support and also cleanup and document the API's.

**Comment by codomania** [comment]
Added subtitle and audio support
9be40d3e1b593e01d84410c68706985355ba38d1
72ca20a6270c2547a94753731cd9849ac19c80b1

Did basic testing with following file and i am able to query all the subtitle, audio and video tracks included in the file.
./gst-play/gst-play --interactive http://trailers.divx.com/divx_prod/divx_plus_hd_showcase/Sintel_DivXPlus_6500kbps.mkv

**Comment by sdroege** [comment]
I took a short look, and API-wise this looks really good already. I found some minor issues, but will take a closer look later and provide comments then.

**Comment by codomania** [comment]
Great. I will continue cleanup code and send you a final one for review..

**Comment by codomania** [comment]
I am getting very close to finish media information and taglist support. So far I have added the following features:

lib/gst/player
1) Media information and taglist retrieval API's. 
2) API to change the current track

gst-play/gst-play:
1) add a keyboard event 'i' to do display the media information. The media information is obtained using the newly added API's. The information contains
- all the streams in media
- current streams
- video/audio/subtitle streams 

gtk-play/gtk-play:
1) Added a popup menu; Right mouse click in the video widget brings a new popup menu with the following selections
    Audio 
    Video
    Subtitle
    Media Information 

Audio/Video/Subtitle menu contains a submenu which list all the tracks. user can change the track by simply clicking the track name.

media information opens a new window with all the stream information.

I have sent a pull request; mediainfo branch in my fork contains all the patches for review. 

Thanks
Brijesh

**Comment by sdroege** [comment]
This is solved now
