### ISSUE TITLE
qt: Seek bar is updated for position changes while dragging it

### ISSUE THREAD

**Issue by sdroege** [sdroege/gst-player#131]
@amorenoc When dragging the seek bar (i.e. clicking on it, not releasing the mouse button and moving it around), the seek bar will jump around because of the position updates.

While the seek bar is dragged, it should not be updated from position updates.

**Comment by sdroege** [comment]
It would also be nice if seeks would happen while dragging :)

**Comment by amorenoc** [comment]
:+1:

**Comment by sdroege** [comment]
48bd41e5018d9bbd7d3fb65603821d7828b1d9e6 fixes this
