### ISSUE TITLE
player.c error on compilation

### ISSUE THREAD

**Issue by cristianastorino** [sdroege/gst-player#140]
player->player = gst_player_new (player->renderer, NULL);

should be  player->player = gst_player_new ();

else I have a compile error

File: player.c, row: 202

**Comment by sdroege** [comment]
Which branch are you using? master requires GStreamer 1.7.1.1 at least, gst-player-0.1 branch requires 1.6.0 and should work fine.

This is the relevant commit that changed things here: https://github.com/sdroege/gst-player/commit/14b945de5a98fe3d3ab306651ad3ecb494a1743d

**Comment by cristianastorino** [comment]
Ok, I tried with branch gst-player-0.1 and it compiles fine
