### ISSUE TITLE
unsatisfied link error

### ISSUE THREAD

**Issue by cristianastorino** [sdroege/gst-player#141]
I got this error when trying to load gstreamer_android compiled with gstreamer_arm_1.7.1:

java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/it.boot.meteo-1/lib/arm/libgstreamer_android.so": 0

**Comment by sdroege** [comment]
Is there anything else in the debug logs? The code in question is here: https://github.com/GStreamer/cerbero/blob/master/data/ndk-build/gstreamer_android-1.0.c.in#L513
It can only return 0 on errors, in which case it also prints what exactly is wrong

**Comment by cristianastorino** [comment]
Solved, I had that class in the wrong folder...
