### ISSUE TITLE
problems with rtmp and buffering

### ISSUE THREAD

**Issue by cristianastorino** [sdroege/gst-player#142]
Hi, I'm trying to include gst-player inside an android app because I need to play a rtmp stream.

Actually, I've got to compile gstreamer 1.6.2 and I was using gst-player-0.1 branch.

From the logs I can see that the stream goes to the paused state when buffering is done, but I don't know why:

http://pastebin.com/NxAzhw7q

And no more logs are shown.

Let me you if you need more info.

Thanks

**Comment by sdroege** [comment]
Based on the buffering signal you don't have to switch states between paused and playing. GstPlayer already does that internally for you.
But that's unrelated to your problem, just a possible simplification for your application. You seem to call play() whenever 100% buffering has happened? Actually you seem to call gst_player_play_internal() directly? Best would be to share the relevant part of your application code too.

**Comment by cristianastorino** [comment]
It was a try, this is the relevant code (actually very simple):
http://pastebin.com/n75mxUm9

I think I miss something somewhere :)

**Comment by sdroege** [comment]
You don't, that should work like this. Can you give me the RTMP URL (is it public?)?

**Comment by cristianastorino** [comment]
this is the url: rtmp://webcam.crisdroid.eu:1935/live/soveria1

**Comment by sdroege** [comment]
Ok, that one works just fine here. Can you send me another debug log, this time the full output from the beginning and everything that follows?

**Comment by cristianastorino** [comment]
this is the full log from the start of the app: http://pastebin.com/d7SGM5C7

**Comment by sdroege** [comment]
Ah that's probably http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=22a0914cce9f6352e3042b9f1f7b9cacac2db0b7

If you downgrade to 1.6.1 this should be fixed, will also be in 1.6.3 and 1.7.2. Unfortunately slipped into those releases.

**Comment by cristianastorino** [comment]
Ok, I compiled 1.6.1 and it seems to work now.

Is is possible to intercept when the stream is actually shown (I would like to show a progress instead of a black screen)?

**Comment by sdroege** [comment]
The video-dimensions-changed signal is emitted whenever the video dimensions change, that should do it
