### ISSUE TITLE
android 4.0.4 issue

### ISSUE THREAD

**Issue by cristianastorino** [sdroege/gst-player#145]
I'm using gst-player on android. On most smartphones there are no issues, but I don't know why on a Galaxy S DUOS (kyleopen) doesn't work.
When the app is launched, only a blank screen is shown (I assume is loading GStreamer libraries).
Maybe the device is not powerful enough to load gstreamer?
This is the logcat: http://pastebin.com/apWs43Pw

**Comment by cristianastorino** [comment]
some more logs: http://pastebin.com/GK1fsQBY
I think the problem is the following line:

01-10 15:57:34.846 17405-17405/it.boot.meteo D/Player: init 1
01-10 15:57:34.876 17446-17446/? A/libc: Fatal signal 13 (SIGPIPE) at 0x00004426 (code=0)

here is the android code:
        Log.d(TAG, "init 1");
        System.loadLibrary("gstreamer_android");
        Log.d(TAG, "init 2");

init2 is never printed, so I think the fatal occurs when loading gstreamer_android.

Let me know if you need others info to solve the problem.

**Comment by sdroege** [comment]
See my reply on the GStreamer mailing list. This is a bug in the device most likely, but we can probably work around it in GStreamer. Completely unrelated to GstPlayer though, and that device is in general powerful enough to handle GStreamer. We're using GStreamer on much slower and older devices :)
