### ISSUE TITLE
configuration failure on Master branch

### ISSUE THREAD

**Issue by kirushyk** [sdroege/gst-player#146]
I tried to configure gst-player but I have error:
`No package 'gstreamer-player-1.0' found`
I need gstreamer-player to build gstreamer-player? (:

**Comment by sdroege** [comment]
The master branch assumes gstreamer from git master (especially gst-plugins-bad). If you have an older version, use the gst-player-0.1 branch (that works with 1.6).

**Comment by kirushyk** [comment]
As I understood, gstreamer-player-1.0 is now part of gst-plugins-bad so this repo will be a set of examples?

**Comment by sdroege** [comment]
Yes, and for a while I will keep the old branch up to date with what is in gst-plugins-bad. And at some point the examples will probably move to a nicer place :)

**Comment by kirushyk** [comment]
Thank you for clarification (: Good luck
