### ISSUE TITLE
ndk-build.cmd finished with non-zero exit value 2

### ISSUE THREAD

**Issue by markdion-vdi** [sdroege/gst-player#148]
I opened the android folder as an existing project in Android Studio and built it. I first got this build error
`Execution failed for task ':app:ndkBuild'.
A problem occurred starting process 'command 'C:\Users\*****\AppData\Local\Android\sdk1\ndk-bundle/ndk-build''`
I think this was because I'm running with Windows, so I needed the .cmd. So I added the .cmd to ndk-build and rebuilt. This time I got a different error:
`Execution failed for task ':app:ndkBuild'.
Process 'command 'C:\Users\*****\AppData\Local\Android\sdk1\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2`
I have been reading that this is a bug with Android Studio because it currently has weak NDK support. But I am assuming [ford-prefect](https://github.com/ford-prefect) didn't check in [this](https://github.com/sdroege/gst-player/commit/9b4c565c9a9fb45e7e71eed35fe51f8faf57a9ac) change without first building it on his machine. So I must be missing a step.

**Comment by sdroege** [comment]
Can you provide the full output from the terminal?

**Comment by markdion-vdi** [comment]
How do I get the full terminal output when building in Android Studio?

**Comment by markdion-vdi** [comment]
When I try and do an `ndk-build` in Command Prompt from the android directory I get this output:
```
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
D:\android-ndk-r10e\build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.
```
This seems to be happening because there is no Application.mk for it to use for the build. Not sure if this is what you wanted...

**Comment by markdion-vdi** [comment]
I navigated to `app\src\main\jni` and this seems to be the right place for the ndk-build. This is the output now: 

```
Package gstreamer-player-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-player-1.0' found
Package gstreamer-player-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-player-1.0' found
gstreamer-1.0-android-arm-1.6.1/share/gst-android/ndk-build//tools/windows/sed: can't read C:/local/gstreamer-1.0-android-arm-1.6.1/lib/pkgconfig/gstreamer-player-1.0.pc: No such file or directory
Package gstreamer-player-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-player-1.0' found
[armeabi] Compile thumb  : gstplayer <= player.c
C:/local/gst-player-gradle/android/app/src/main/jni/player.c:28:31: fatal error: gst/player/player.h: No such file or directory
 #include <gst/player/player.h>
                               ^
compilation terminated.
make.exe: *** [C:/local/gst-player-gradle/android/app/src/main/obj/local/armeabi/objs/gstplayer/player.o] Error 1
```

**Comment by markdion-vdi** [comment]
The issue is that my GStreamer sdk folder `gstreamer-1.0-android-arm-1.6.1` doesn't contain `gstreamer-player-1.0.pc`, and `Android.mk` asks for it. Here is the bottom of that file.

```
GSTREAMER_NDK_BUILD_PATH  := $(GSTREAMER_ROOT)/share/gst-android/ndk-build/

include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS         := $(GSTREAMER_PLUGINS_CORE) $(GSTREAMER_PLUGINS_PLAYBACK) $(GSTREAMER_PLUGINS_CODECS) $(GSTREAMER_PLUGINS_NET) $(GSTREAMER_PLUGINS_SYS) $(GSTREAMER_PLUGINS_CODECS_RESTRICTED) $(GSTREAMER_CODECS_GPL) $(GSTREAMER_PLUGINS_ENCODING) $(GSTREAMER_PLUGINS_VIS) $(GSTREAMER_PLUGINS_EFFECTS) $(GSTREAMER_PLUGINS_NET_RESTRICTED)
GSTREAMER_EXTRA_DEPS      := gstreamer-player-1.0 gstreamer-video-1.0 glib-2.0

include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk
```

**Comment by sdroege** [comment]
Yes you need 1.7.90 or newer for the master branch of gst-player. For 1.6, use the gst-player-0.1 branch

**Comment by markdion-vdi** [comment]
Ah ok. It works now with 1.8.0, thanks!

**Comment by vivekananthachari** [comment]
Error:(158) *** Android NDK: Aborting.    .  Stop.
