### ISSUE TITLE
Xcode fails to build 

### ISSUE THREAD

**Issue by Cowprod** [sdroege/gst-player#151]
With gstreamer-1.0-devel-1.7.91-ios-universal.pkg build fails

Undefined symbols for architecture arm64: "_gst_plugin_liveadder_register", referenced from: _gst_ios_init in gst_ios_init.o "_gst_plugin_fragmented_register", referenced from: _gst_ios_init in gst_ios_init.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sdroege** [comment]
Yeah the gst_ios_main.h / .m have to be updated for 1.6+ from the binaries. Want to send a pull request?

**Comment by Cowprod** [comment]
I'm really sorry but I think it is out of my competences for now.
I reinstall 1.5.9.1 and tutorials build, I don't know if I could have bert performances with 1.7.91, I use gstreamer to play RTSP stream on IOS

**Comment by sdroege** [comment]
Yes you will have better performance with 1.7/1.8 on iOS, both with RTP/RTSP but also H264 decoding related.

Basically you just have to replace the gst_ios_main.m / .h files with the ones from the GStreamer binaries, and make sure the .h file enables all the playback related plugins again. I can help you with that :)

**Comment by Cowprod** [comment]
ok so let's try ;)

I try to do this today.

I have another question related to latency (to set it lower than the
default 2 seconds), I stuck on source-setup, what is the best to
communicate about that point ?

2016-03-24 10:42 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by sdroege** [comment]
You can get playbin from GstPlayer with get_pipeline(), and then connect to the source-setup signal to configure the RTSP latency for now. At some point GstPlayer should provide some API for that.

**Comment by Cowprod** [comment]
I already use playbin

pipeline = gst_parse_launch("playbin uri=rtsp://192.168.2.160:554/stream ",
&error);

and catch the signal

g_signal_connect (pipeline, "source-setup", G_CALLBACK (source_setup_cb),
NULL);

I dont know if arguments are corrects but the callback is fired

static void source_setup_cb (GstBus *bus, GstMessage *msg, GStreamerBackend
*self)

{

    GST_DEBUG ("source-setup\n");

 }

I stuck here



2016-03-24 11:13 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by sdroege** [comment]
Why are you using playbin directly instead of using GstPlayer, and then report an issue here? :)

it would be void source_setup_cb (GstElement *playbin, GstElement *source, gpointer user_data).

**Comment by Cowprod** [comment]
It is why I ask you where communicate about that :)

I start another (light) project "from scratch" based on ios sdk tutorials

2016-03-24 11:37 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by sdroege** [comment]
Best to ask on https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel but for 99% of the cases where you use playbin, GstPlayer can be used and should make your life easier

**Comment by Cowprod** [comment]
So I go back to GstPlayer :)

2016-03-24 11:57 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by Cowprod** [comment]
oups I made a git clone of gst-player on my office mac and now I have 'gst/player/player.h' file not found on top of VideoViewController.h
(framework 1.5.9.1 installed on this computer)

**Comment by sdroege** [comment]
For the GstPlayer master branch you need GStreamer 1.7.90 or newer

**Comment by Cowprod** [comment]
ok ! I update :)

**Comment by Cowprod** [comment]
ok :) we're back on the "_gst_plugin_liveadder_register" issue :)

I try to find and replace gst_ios_main.m / .h files with the ones from the GStreamer binaries

**Comment by Cowprod** [comment]
i do not find any gst_ios_main.* file... gst-ios_init.m / .h ?

**Comment by Cowprod** [comment]
Sebastian I can build if I comment this 2 lines

#define GST_IOS_PLUGINS_EFFECTS
#define GST_IOS_PLUGINS_CODECS

I add my RTSP stream to the list and it is played (with the default 2s latency)

Could you help me to find the gst_ios_main.m / .h files to replace ?

**Comment by sdroege** [comment]
Yes, gst_ios_init, not main. You have to update the ones from the project with the ones from the new GStreamer binaries. And then make the #defines in the header look the same.

**Comment by Cowprod** [comment]
2016-03-24 19:25 GMT+01:00 Sebastian Dröge <notifications@github.com>:

> GStreamer binaries


for GStreamer binaries you mean in the exmaples that come to the desktop
when I install

https://gstreamer.freedesktop.org/data/pkg/ios/1.7.91/

or from cerbero ( cerbero/data/xcode/templates/ios/GStreamer\
Base.xctemplate/gst_ios_init.h )

or it is the same

**Comment by sdroege** [comment]
The first. The second is only a template that is filled in during the build of the GStreamer binaries and then results in the bigger files from the binaries.

**Comment by Cowprod** [comment]
It is what I just saw :)

so with .m files from tutorials and with this in .h

#ifndef __GST_IOS_INIT_H__

#define __GST_IOS_INIT_H__


#include <gst/gst.h>


G_BEGIN_DECLS


#define GST_G_IO_MODULE_DECLARE(name) \

extern void G_PASTE(g_io_module_, G_PASTE(name, _load_static)) (void)

#define GST_G_IO_MODULE_LOAD(name) \

G_PASTE(g_io_module_, G_PASTE(name, _load_static)) ()

/* Uncomment each line to enable the plugin categories that your
application needs.

 * You can also enable individual plugins. See gst_ios_init.c to see their
names

 */

#define GST_IOS_PLUGINS_CORE

#define GST_IOS_PLUGINS_CAPTURE

#define GST_IOS_PLUGINS_CODECS_RESTRICTED

#define GST_IOS_PLUGINS_ENCODING

#define GST_IOS_PLUGINS_DVD

#define GST_IOS_PLUGINS_CODECS_GPL

#define GST_IOS_PLUGINS_NET_RESTRICTED

#define GST_IOS_PLUGINS_SYS

#define GST_IOS_PLUGINS_VIS

#define GST_IOS_PLUGINS_PLAYBACK

#define GST_IOS_PLUGINS_EFFECTS

#define GST_IOS_PLUGINS_CODECS

#define GST_IOS_PLUGINS_NET

#define GST_IOS_GIO_MODULE_GNUTLS

void gst_ios_init ();

G_END_DECLS

#endif


Undefined symbols for architecture armv7:

  "_gst_plugin_coreindexers_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_ffmpegcolorspace_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_ffmpeg_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_indvd_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_camerabin2_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_applemedia_nonpublic_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_uridecodebin_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_faceoverlay_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_jp2kdecimator_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_scaletempo_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_rtpvp8_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_ivfparse_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_liveadder_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_rtpmux_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_stereo_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_mpegdemux2_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_dccp_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_mpegaudioparse_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_fragmented_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_eglglessink_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_videomeasure_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_hdvparse_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_jp2k_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_videosignal_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_nuvdemux_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_tta_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_registry_get_default", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_dvdread_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_mve_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_cdxaparse_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_nsf_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_vmnc_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_gstrtpmanager_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_annodex_register", referenced from:

      _gst_ios_init in gst_ios_init.o

  "_gst_plugin_vp8_register", referenced from:

      _gst_ios_init in gst_ios_init.o

ld: symbol(s) not found for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see
invocation)

2016-03-25 9:55 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by sdroege** [comment]
The things you copied there are not from the 1.7 binaries, but from some old 0.10 version.

**Comment by Cowprod** [comment]
oups sorry

I was sure that the files on my desktop came from

gstreamer-1.0-devel-1.7.91-ios-universal.pkg

too tired :)

I created a new projet from gstreamer template and copied the files in
gst-player project, uncommented all the #define...

The project build perfectly, my stream play (with the 2 second default
latency of course)

2016-03-25 10:19 GMT+01:00 Sebastian Dröge <notifications@github.com>:

**Comment by Cowprod** [comment]
Sebastian do I comment this #define in my fork as your original project before doing the pull-request ? (new to Git...I hope it is the good methode...)

//#define GST_IOS_PLUGINS_CAPTURE
//#define GST_IOS_PLUGINS_ENCODING
//#define GST_IOS_PLUGINS_EDITING

**Comment by sdroege** [comment]
Yes, those plugins just take space and are not going to be used by the player.

**Comment by Cowprod** [comment]
done for the 2 first one but #define GST_IOS_PLUGINS_EDITING is not in the .h file from the binaries.
do I add it commented  or not at all ?

**Comment by sdroege** [comment]
You can omit it, yes

**Comment by Cowprod** [comment]
done, and pull-request added
