### ISSUE TITLE
Android Studio + OSX build failed

### ISSUE THREAD

**Issue by dvv47** [sdroege/gst-player#152]
When i tried update to latest repository version i got a lot of errors like
#include <gst/player/player.h> not found.

But i have setup GSTREAMER_ROOT_ANDROID
and have pkg-config installed in system

and very big list of strange errors like
/bin/sh: - : invalid option
Usage:	/bin/sh [GNU long option] [option] ...
or
/bin/sh: i: command not found
make: [genstatic_armeabi] Error 127 (ignored)

So for me resolve of those issues was adding to
task ndkBuild()

environment PATH: "/usr/bin:/opt/local/bin:/opt/local/sbin${File.pathSeparator}${System.getenv("PATH")}"

this resolve bug with #include <gst/player/player.h> not found.
Its strange becouse this already setuped by .bash_profile and visible from Android Studio terminal after "export" command, bug after that i think build ssytem found pkg-config and all works fine.

next problem i resolve in two steps,
1. build system can't find SED
2. OSX sed command has different syntaxis with -i parameter. Its require to specify prefix for backup file.
and works well /opt/local/bin/gsed

result:
`task ndkClean(type: Exec, description: 'Clean JNI code built via NDK') {
        environment NDK_HOST_SED: "/opt/local/bin/gsed"
        environment PATH: "/usr/bin:/opt/local/bin:/opt/local/sbin${File.pathSeparator}${System.getenv("PATH")}"
        commandLine getNdkCommandLine(android.ndkDirectory, 'clean')
    }`

**Comment by sdroege** [comment]
The sed problem is Google breaking things with the r11 NDK: https://bugzilla.gnome.org/show_bug.cgi?id=763902

We'll have to find a solution for that one, one way or another. It's tracked in the GStreamer bugzilla.
