### ISSUE TITLE
Can not build SDK

### ISSUE THREAD

**Issue by hoanhnv** [sdroege/gst-player#163]
Hi Guy,
I have clone source then build but not sucess,it always have error as below
'/Users/mac/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/Headers/iconv.h:142:8: Redefinition of 'iconv_hooks'
if i have build source from sample after open gstreamer-sdk-devel-2013.6-ios-universal.dmg file it not error.
pls help me resolve it,thanks!

**Comment by sdroege** [comment]
The "GStreamer SDK" from gstreamer.com is completely outdated and done by some companies, it's unrelated to the GStreamer project.

Get up-to-date binaries for iOS from here https://gstreamer.freedesktop.org/data/pkg/ios/1.8.3/ (that's the latest as of now)

**Comment by hoanhnv** [comment]
thanks you!,
I have build success it.
