### ISSUE TITLE
Player view can not resume after gst_player_pause call

### ISSUE THREAD

**Issue by hoanhnv** [sdroege/gst-player#165]
Hi
When i tap pause button then tap play button to resume but player still not redraw,i saw consolog it gst-play still running.
I using source sample and i use to play rtsp streaming

**Comment by sdroege** [comment]
On which stream, with which application, which GStreamer version and on which platform is that?

**Comment by hoanhnv** [comment]
I build for iOS platform,GStreamer gstreamer-1.0-devel-1.8.3-ios-universal.pkg
this stream link demo rtsp://vudv:vudv@14.177.250.18:554/cam/realmonitor?channel=2&subtype=0

**Comment by hoanhnv** [comment]
**Hi Guy,
I saw log and that has error as below**
[00m [00m          gst-player gstplayer.c:871:emit_error:<player0>[00m Error: Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source: Could not read from resource.
Could not read from resource.
gstrtspsrc.c(5670): gst_rtspsrc_send (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source:

**I think maybe issue of server streaming,so u can confirm it,i not sure this issue.**

**Comment by sdroege** [comment]
Yes that's unrelated to GstPlayer. The problem is probably that you're pausing for too long and then the RTSP connection gets cut. If you still think there's an actual bug somewhere, please report it here: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer
