### ISSUE TITLE
Urgent help please!   Image transfer does not occur.

### ISSUE THREAD

**Issue by zafersn** [sdroege/gst-player#166]
Hi friend.

I have a question. 

I used the "gstreamer-sdk-android-arm-release-2013.61" library before and I compiled in NDK 9. I was transferring video to android on raspberry pi. I gave up using this version because of google play store libpng problem. Despite the running of the program. I can not see the image. The version I'm using is "gstreamer-1.0-android-arm-1.8.0". And the NDK version I compiled is NDK 10. Where am I making the mistake of you? There's just no video display on screen.

Android studio logcat posts below:
http://paste.ubuntu.com/23616117/

I modified main / jni / tutorial-3.c and added the following code

/* Build pipeline */
  data->pipeline = gst_parse_launch("udpsrc port=8554 caps=\"application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, sprop-parameter-sets=\\\"J2QAFKwrQLj/LwDxImo\\\\=\\\\,KO4fLA\\\\=\\\\=\\\"\", payload=96\" ! rtph264depay ! ffdec_h264 ! autovideosink sync=false", &error);

tutorial-3.c : 
http://paste.ubuntu.com/23616131/

and Android.mk file : 

http://paste.ubuntu.com/23616134/

build.gradle file: 

http://paste.ubuntu.com/23616170/

@sdroege  thankyou
I do not know English very well. I hope. I have used a descriptive language.

**Comment by sdroege** [comment]
This is not a support forum, and your request does not have anything to do with GstPlayer either.
