### ISSUE TITLE
gst-player - ndk-build error

### ISSUE THREAD

**Issue by rvinoth83** [sdroege/gst-player#167]
Hi,

Trying to build the gst-player for android in command line. Facing following error.
How to fix it

[armeabi] Compile thumb  : gstplayer <= player.c
GStreamer      : [GEN] => gst-build-armeabi/gstreamer_android.c
GStreamer      : [COMPILE] => gst-build-armeabi/gstreamer_android.c
GStreamer      : [LINK] => gst-build-armeabi/libgstreamer_android.so
make.exe: *** [copyjavasource_armeabi] Error 1

Regards
Vinoth

**Comment by sdroege** [comment]
See https://github.com/sdroege/gst-launch-remote/issues/7#issuecomment-267612814

**Comment by sdroege** [comment]
Solved now. The new location for the Android GstPlayer app is here now though: https://cgit.freedesktop.org/gstreamer/gst-examples/
