### ISSUE TITLE
Record stream

### ISSUE THREAD

**Issue by LPFinch** [sdroege/gst-player#169]
Hi, thanks for your work! 
1. I need record RTSP stream into sdcard(mp4, Android).
2. I need extract frame(screenshot) from RTSP stream(bitmap, Android).
Can you make tutorial or little example here? Please show me a way.
Thanks.

**Comment by sdroege** [comment]
That's outside the scope of GstPlayer. Please ask on the GStreamer mailing list here https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel
