### ISSUE TITLE
Help with dewarp plugin

### ISSUE THREAD

**Issue by ghafran** [sdroege/gst-player#170]
I know this is in the wrong rep, but can anyone get ```dewarp``` plugin working?
```
gst-launch-1.0 videotestsrc ! fisheye ! dewarp ! videoconvert ! autovideosink
```
Thanks.

**Comment by sdroege** [comment]
Please ask this on the [GStreamer development mailing list](http://lists.freedesktop.org/mailman/listinfo/gstreamer-devel) or the GStreamer IRC (#gstreamer on Freenode).
