### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by IKepeRR** [sdroege/gst-player#30]
Good morning. I downloaded the ios project but can't build it cause of lib linking problems:

Undefined symbols for architecture armv7:
  "_gst_player_media_info_get_type", referenced from:
      _gst_player_class_init in gstplayer.o
  "_gst_player_media_info_new", referenced from:
      _gst_player_media_info_create in gstplayer.o
  "_gst_player_stream_info_new", referenced from:
      _gst_player_streams_info_create in gstplayer.o
  "_gst_player_stream_info_get_tags", referenced from:
      _stream_info_get_codec in gstplayer.o
  "_gst_player_media_info_get_stream_list", referenced from:
      _gst_player_stream_info_find in gstplayer.o
  "_gst_player_stream_info_get_caps", referenced from:
      _stream_info_get_codec in gstplayer.o
  "_gst_player_stream_info_get_stream_type", referenced from:
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _gst_player_streams_info_create in gstplayer.o
  "_gst_player_video_info_get_type", referenced from:
      _gst_player_get_current_video_track in gstplayer.o
      _video_changed_cb in gstplayer.o
      _video_tags_changed_cb in gstplayer.o
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _get_caps in gstplayer.o
      _stream_info_get_codec in gstplayer.o
      _gst_player_stream_info_update in gstplayer.o
      ...
  "_gst_player_audio_info_get_type", referenced from:
      _gst_player_get_current_audio_track in gstplayer.o
      _audio_changed_cb in gstplayer.o
      _audio_tags_changed_cb in gstplayer.o
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _get_caps in gstplayer.o
      _stream_info_get_codec in gstplayer.o
      _gst_player_stream_info_update in gstplayer.o
      ...
  "_gst_player_subtitle_info_get_type", referenced from:
      _gst_player_get_current_subtitle_track in gstplayer.o
      _subtitle_changed_cb in gstplayer.o
      _subtitle_tags_changed_cb in gstplayer.o
      _gst_player_media_info_create in gstplayer.o
      _gst_player_class_init in gstplayer.o
  "_gst_player_stream_info_get_index", referenced from:
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
  "_gst_player_stream_info_copy", referenced from:
      _gst_player_stream_info_get_current in gstplayer.o
  "_gst_player_media_info_copy", referenced from:
      _gst_player_get_media_info in gstplayer.o
      _emit_media_info_updated_signal in gstplayer.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you say what should I do to fix it?

**Comment by sdroege** [comment]
Thanks for reporting, this should be fixed now. Sorry!

As you can see in the commit message, the new media info API is not yet exposed by the JNI bindings.

**Comment by IKepeRR** [comment]
It is an iOS project((
