### ISSUE TITLE
Build issue iOS Project.

### ISSUE THREAD

**Issue by IKepeRR** [sdroege/gst-player#33]
Sry for repeating, but last issue I created with lib linking was for iOS project :(

**Comment by sdroege** [comment]
Ah, I don't have access to my Mac currently. Can you update the iOS project to include the new files, and then send a pull request?

**Comment by IKepeRR** [comment]
What new files do you mean?

**Comment by sdroege** [comment]
Can you send a pull request with those changes?

**Comment by IKepeRR** [comment]
Yeah, I sent it already.

**Comment by IKepeRR** [comment]
One more problem - when I try to change slider while playing .ts file - video starts playing from the beginning. Is it a normal behavior?

**Comment by sdroege** [comment]
Where did you send the pull request?

No, that's not normal behaviour. It would be a bug in tsdemux probably :)

**Comment by IKepeRR** [comment]
I pressed pull in my xcode project.

p.s. So there is no way to fix it?

**Comment by sdroege** [comment]
That's not how pull requests work :) You would have to push the changes to some branch here on github, and then click on the "create pull request" button.


Sure there's a way to fix it. Inside tsdemux. Can you report a bug with a testcase (the file in question) at http://bugzilla.gnome.org?

**Comment by IKepeRR** [comment]
So I should just report bug and w8 until they fix it? :)

**Comment by sdroege** [comment]
Can you provide the file in question to me? Then I can report a bug

**Comment by IKepeRR** [comment]
What do u mean? Should I write description of problem here or...?

**Comment by sdroege** [comment]
You say it happens on a mpeg ts file, I would need access to that file. Because in general seeking on mpeg ts seems to work

**Comment by IKepeRR** [comment]
ok. Where could I send u file?

**Comment by sdroege** [comment]
Dropbox or similar for example

**Comment by IKepeRR** [comment]
Change end of file to .ts)))
![1](https://cloud.githubusercontent.com/assets/5120760/7489481/d5bda634-f3df-11e4-8912-9c94cb3ab4e4.gif)

**Comment by IKepeRR** [comment]
![1](https://cloud.githubusercontent.com/assets/5120760/7489491/ef489a1e-f3df-11e4-8eea-fc3a7a97a7ba.gif)

**Comment by sdroege** [comment]
And please also provide your changes to the XCode iOS project :)

**Comment by IKepeRR** [comment]
I changed a lot already, it's a part of my project now.(( link to file - https://www.dropbox.com/s/0kvbi04y95x7p41/1.ts?dl=0

**Comment by sdroege** [comment]
That file works fine for me, including seeking. Anyway, this ticket here is for the iOS build failure. Would be great if you could provide a patch for that, otherwise we'll have to wait until someone else does.

**Comment by IKepeRR** [comment]
What project do you use?

**Comment by IKepeRR** [comment]
Tried to push my branch but got this error - http://joxi.ru/zANQ49wSzEY829

**Comment by sdroege** [comment]
See https://help.github.com/articles/fork-a-repo/ and https://help.github.com/articles/using-pull-requests/

**Comment by IKepeRR** [comment]
Look at screenshot while seeking - http://joxi.ru/5mdGoLDsL854r1
Something wrong with seeking time I think. Where should be the problem?

**Comment by sdroege** [comment]
That problem would be in GstPlayer somewhere. Check which value is passed to gst_player_seek() from the UI, maybe that is wrong already.

**Comment by IKepeRR** [comment]
http://joxi.ru/8An3WkKfkN6OrO. time_slider values is in milliseconds I guess, so to gst_player_seek() is passed value milliseconds*1000000. Is it right?

**Comment by sdroege** [comment]
Yes, so the slider gives us an incredibly high milliseconds value?

**Comment by IKepeRR** [comment]
Yes, for example for 10sec, the value passing to gst_player_seek is 10000000000

**Comment by sdroege** [comment]
Sounds correct, where does that weird value in your debug log come from?

**Comment by IKepeRR** [comment]
When I am sliding time controller while playing video file

**Comment by sdroege** [comment]
So the UI gives us wrong values then?

**Comment by IKepeRR** [comment]
I think player give us something wrong. We checked ui values already, aren't we?

**Comment by IKepeRR** [comment]
I think I know where is the problem, but dont know how to fix it. Value becomes wrong while converting long to GstClockTime. 
gst_player_seek (GstPlayer * self, GstClockTime position)

and in the UI we call - gst_player_seek (player, ((long)time_slider.value) * 1000000);

Do u know how to do right converting?

**Comment by IKepeRR** [comment]
I fixed it:
 GstClockTime seekPosition= (GstClockTime)(time_slider.value * 1000000);

**Comment by sdroege** [comment]
Yes that makes some sense. Do you want to provide a pull request or should I just fix it?

**Comment by IKepeRR** [comment]
Better u)))

**Comment by sdroege** [comment]
Ok, please check if this fixes it. And also please open new tickets in the future for new problems :)
