### ISSUE TITLE
Gradle task error

### ISSUE THREAD

**Issue by wandering7man** [sdroege/gst-player#36]
I'll set all variables and still got error on  "compileTask -> compileTask.dependsOn ndkBuild" like this:
Error:Execution failed for task ':app:ndkBuild'.
> java.lang.NullPointerException (no error message)
Any ideas?:(

**Comment by ened** [comment]
Can you post the contents of local.properties?

**Comment by ened** [comment]
@wandering7man , here is what local.properties looks like for me (on OS X):

```
sdk.dir=/usr/local/Cellar/android-sdk/24.1.2
ndk.dir=/usr/local/Cellar/android-ndk/r10d
gstreamer.arm.dir=/Users/sebastian/tmp/gstreamer-1.0-android-arm-release-1.4.5/
gstreamer.armv7.dir=/Users/sebastian/tmp/gstreamer-1.0-android-armv7-release-1.4.5/
gstreamer.x86.dir=/Users/sebastian/tmp/gstreamer-1.0-android-x86-release-1.4.5/
ndk.extraPath=/usr/local/bin/
```

The error message you wrote should be triggered by undefined properties in `local.properties`.

**Comment by wandering7man** [comment]
My local.properties(Win 8.1)
sdk.dir=G\:\\android-sdk-new
ndk.dir=G\:\\android-ndk-r10d
gstreamer.armeabi.dir=G\:\\gst-player\\gstreamer-1.0-android-arm-release-1.4.5
gstreamer.armeabi-v7a.dir=G\:\\gst-player\\gstreamer-1.0-android-armv7-release-1.4.5
gstreamer.x86.dir=G\:\\gst-player\\gstreamer-1.0-android-x86-release-1.4.5

**Comment by ened** [comment]
Yes, there it is, please change:

`gstreamer.armeabi.dir` -> `gstreamer.arm.dir`
`gstreamer.armeabi-v7a.dir` -> `gstreamer.armv7.dir`

**Comment by wandering7man** [comment]
Thank you, it is work:). but one thing in Win OS: 

if (Os.isFamily(Os.FAMILY_WINDOWS)) {
     commandLine "${ndkDir}/ndk-build.cmd", '-C', file('src/main/jni').absolutePath
} else {
     commandLine "${ndkDir}/ndk-build", '-C', file('src/main/jni').absolutePath
}

**Comment by ened** [comment]
Wonderful, we will add that. Thanks.
