### ISSUE TITLE
Autogenerate Android JNI bindings from GObject-Introspection information

### ISSUE THREAD

**Issue by sdroege** [sdroege/gst-player#39]
Could be based on this: https://github.com/EricssonResearch/openwebrtc/tree/master/bindings/java

Now that we have media-info, we will also have to expose some minimal GStreamer bindings (for taglists, samples, caps, buffers, structures)

**Comment by codomania** [comment]
:+1:  i was wanting to learn into Android stuff.. if anyone interested then pick it up otherwise i may take this as opportunity to get my hand dirty in Android :)

**Comment by ened** [comment]
Could this handle a transformation of those GObjects (for media info) - wouldn't that mean a lot of manual transformation still?

**Comment by sdroege** [comment]
Yes, that's the plan. Handling all this automatically. That's how it is already successfully done e.g. for the C# and Python bindings.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765318 and related bugs. This should be handled in GStreamer now
