### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by wandering7man** [sdroege/gst-player#41]
I use stream by url rstp://.... , it's work good, but when i'll press back, or close fragment(or activtiy), i got crash in librariy with tonn of logs, and i can't find reason. Any help will be appriciated.
full log: https://docs.google.com/document/d/1S9uTBiBwKIynZOjaz685lXhttwxgjpa3ZQMpP0Zfh2Q/edit?usp=sharing

**Comment by sdroege** [comment]
That looks like a problem in GStreamer's androidmedia plugin, in the MediaCodec decoder. Please report that at https://bugzilla.gnome.org against GStreamer/gst-plugins-bad and include a native backtrace and details about your device in the bug report.
