### ISSUE TITLE
add playlist support

### ISSUE THREAD

**Issue by amorenoc** [sdroege/gst-player#43]
Current gst-player is missing playlist handling capabilities, and would be very convenient to have an API to load a list of media content to play.
Media content can be added by appending or inserting the uri of the media file into a playlist object. The playlist could then be attached with a property to the player.

The playlist class should also support reading from a playlist file (by passing a url and a format string) and append new items to the list. This would require to parse common playlist file formats e.g. m3u.
Basic functions like play in sequential or shuffled order would be needed too. 

We could start by looking at Totem playlist implementation (https://developer.gnome.org/totem-pl-parser/3.10/TotemPlPlaylist.html)

**Comment by sdroege** [comment]
Sounds useful but the idea is to add some kind of controller object around GstPlayer that would handle a playlist and the underlying GstPlayer instance somehow.
Or maybe it can also be part of GstPlayer itself.

Parsing actual playlist files is secondary

**Comment by hadess** [comment]
I think this is probably best left up to the application, or what you provide should be an interface base class. In totem for example, we'd store a GrlMedia into the playlist, not URIs, or other metadata.

This is an example API:
https://git.gnome.org/browse/totem/tree/src/totem-playlist.h
which has stood the test of time.

The GstPlayer would then ask you whether for the next video to play at the end of a particular video, or whether there are next/previous items. A linked-list with helper functions, in short.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765304
