### ISSUE TITLE
playing .ts files [Android]

### ISSUE THREAD

**Issue by wandering7man** [sdroege/gst-player#47]
Play video from uri "file:///storage/emulated/0/file.ts" don't work, just nothing happen, no erros, no logs, but video streaming from uri "rtsp://..blabla", "file:///storage/emulated/0//Media/07.mp4", work perfect, and other video formats(like mp4,avi, etc..). Any help will be appriciated.

**Comment by sdroege** [comment]
Can you get a GStreamer debug log (on Android you can call gst_debug_set_default_threshold(GST_LEVEL_DEBUG) somewhere before calling play())? Can you also test if it works on a different platform, e.g. Linux/OSX/Windows with the same GStreamer version? Which GStreamer version are you using?

**Comment by wandering7man** [comment]
>FAILED : Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
    Your GStreamer installation is missing a plug-in.
    gsturidecodebin.c(990): no_more_pads_full (): /GstPlayBin:playbin/GstURIDeco
05-13 22:13:00.758    8246-9168/org.freedesktop.gstreamer.play D/﹕ deBin:uridecodebin0:
    no suitable plugins found

**Comment by sdroege** [comment]
Can you provide the ts file in question? Does it work on Linux/OSX/Windows with GStreamer?

**Comment by wandering7man** [comment]
https://www.dropbox.com/s/0kvbi04y95x7p41/1.ts?dl=0, it's work on iOS :), can't test on other platforms(

**Comment by sdroege** [comment]
Ok, can you get me a complete GStreamer debug log on Android then? Call gst_debug_set_default_threshold(GST_LEVEL_DEBUG) before gst_player_play(), and provide all the output that is dumped into "adb logcat" :)

**Comment by wandering7man** [comment]
@sdroege, don't understand, like this? 
>static void
native_play (JNIEnv * env, jobject thiz)
{
  Player *player = GET_CUSTOM_DATA (env, thiz, native_player_field_id);

  if (!player)
    return;
  gst_debug_set_default_threshold(GST_LEVEL_DEBUG)
  gst_player_play (player->player);
}

**Comment by sdroege** [comment]
Yes, for example.

**Comment by wandering7man** [comment]
@sdroege hothing happen in logcat :(.

**Comment by sdroege** [comment]
Did you use the "release" GStreamer binaries, or the debug ones? Sounds like the former. Try the others debug ones :)

**Comment by wandering7man** [comment]
I change it to debug, here log:
https://docs.google.com/document/d/1qDYdcBDSKXy_SqX-XWsFI5OCskgL7NJfJ2IS2MLgDP4/edit

**Comment by sdroege** [comment]
can you provide it as a plaintext file somewhere, e.g. in a gist?

**Comment by wandering7man** [comment]
@sdroege , https://drive.google.com/file/d/0B1lqNSMbynqhR3RtY3g2MUVUbFk/view?usp=sharing
