### ISSUE TITLE
external subtitle unit test

### ISSUE THREAD

**Issue by codomania** [sdroege/gst-player#65]
FYI, i was working on developing external subtitle unit test and found some minor issue with handling invalid suburis. I have traced down the issue in gst-plugins-base https://bugzilla.gnome.org/show_bug.cgi?id=751118. Once this gets fixed in upstream then we may also need to make some smaller changes in our libs to reflect it. e.g currently we are returning self->suburi when user queries the current suburi but this need to be changed so that we query the suburi from playbin's "current-suburi" property to get the correct state.

**Comment by sdroege** [comment]
Thanks, I'll take a look at that bug in the next days. Weird that nobody else noticed that yet :)

**Comment by sdroege** [comment]
This should be ok now
