### ISSUE TITLE
autogen.sh errors: *DOC* does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by knocte** [sdroege/gst-player#67]
$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:10: installing './compile'
configure.ac:10: installing './config.guess'
configure.ac:10: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
docs/Makefile.am:1: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
gtk-doc.make:7: error: GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL
docs/lib/Makefile.am:86:   'gtk-doc.make' included from here
gtk-doc.make:59: error: GTK_DOC_BUILD_HTML does not appear in AM_CONDITIONAL
docs/lib/Makefile.am:86:   'gtk-doc.make' included from here
gtk-doc.make:64: error: GTK_DOC_BUILD_PDF does not appear in AM_CONDITIONAL
docs/lib/Makefile.am:86:   'gtk-doc.make' included from here
gtk-doc.make:73: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
docs/lib/Makefile.am:86:   'gtk-doc.make' included from here
gtk-doc.make:294: error: HAVE_GTK_DOC does not appear in AM_CONDITIONAL
docs/lib/Makefile.am:86:   'gtk-doc.make' included from here
docs/lib/Makefile.am:99: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
gst-play/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1

**Comment by sdroege** [comment]
Do you have gtk-doc installed? /usr/share/aclocal/gtk-doc.m4 should provide all this. I've added it to git now

**Comment by knocte** [comment]
I guess I didn't have it. I've pulled latest master, and it works now, thanks

**Comment by sdroege** [comment]
If you plan generating C# bindings, feel free to send me a pull request with them :)
