### ISSUE TITLE
mute property changes volume

### ISSUE THREAD

**Issue by amorenoc** [sdroege/gst-player#71]
playbin documentation says that mute property "Mute the audio channel without changing the volume." but for some reason once I set mute property to true, volume changes to 0.0, and then it remains that way after unsetting mute. gst-player does not seem to modify this behaviour so the problem isn't there.

**Comment by sdroege** [comment]
Which platform is this on? Linux with PulseAudio?

**Comment by amorenoc** [comment]
on Mac OS X, using GStreamer 1.5.2.

**Comment by sdroege** [comment]
Can you file a bug at http://bugzilla.gnome.org against GStreamer? That's either a bug in osxaudiosink, or in the volume element.

**Comment by amorenoc** [comment]
Sure.

**Comment by sdroege** [comment]
Should be solved there now, thanks for reporting :)

**Comment by amorenoc** [comment]
So fast! Thanks for fixing it :+1:
