### ISSUE TITLE
unit test "test_play_backward_rate" fails

### ISSUE THREAD

**Issue by JulienIsorce** [sdroege/gst-player#79]
unit test test_play_backward_rate fails here with :

player.c:1106:F:general:test_play_backward_rate:0: 'GPOINTER_TO_INT (state.test_data) & 0xf' (2) is not equal to '10' (10)

**Comment by codomania** [comment]
Yes this is known issue. It's in my TODO list but patches are always welcome :) 

-Brijesh

**Comment by zzoon** [comment]
This fails because it's trying to seek with rate before seeking 20% done.
gst_player_set_rate should be called after seeking 20% done.

Can I provide a patch? :-)
There are a other little patches also in the testcase.

**Comment by sdroege** [comment]
Sure, a patch would be great :)

**Comment by sdroege** [comment]
This is fixed now:

commit 06d8124396d3c90f04d42b201f05a7722d7e07a7
Author: Hyunjun Ko <zzoonis@gmail.com>
Date:   Mon Sep 21 21:04:46 2015 +0900

    tests: fix a failure of test_play_backward_rate
    
    1. Setting 0.2 as an initial seek.
    2. Calls gst_player_set_rate after initial seeking done.
