### ISSUE TITLE
[iOS] Build Issue: Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by TrungDoan** [sdroege/gst-player#82]
Hi guys,
Sorry for asking this issue again because someone asked before. But my issue is different a bit.
I pulled the latest code from here and tried to build without any change. But i always get this issue. 
My development environment:
- Xcode: 6.4
- MacOS X: 10.10.4
- GStreamer: 1.5.2

Here the issue log:
ld: warning: could not create compact unwind for .LFB3: non-standard register 5 being saved in prolog
Undefined symbols for architecture i386:
  "_gst_player_audio_info_get_type", referenced from:
      _gst_player_get_current_audio_track in gstplayer.o
      _gst_player_set_audio_track in gstplayer.o
      _gst_player_class_init in gstplayer.o
      _audio_changed_cb in gstplayer.o
      _audio_tags_changed_cb in gstplayer.o
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _get_caps in gstplayer.o
      ...
  "_gst_player_get_audio_streams", referenced from:
      _get_from_tags in gstplayer.o
  "_gst_player_get_video_streams", referenced from:
      _get_from_tags in gstplayer.o
  "_gst_player_media_info_copy", referenced from:
      _gst_player_get_media_info in gstplayer.o
      _emit_media_info_updated_signal in gstplayer.o
  "_gst_player_media_info_get_stream_list", referenced from:
      _gst_player_stream_info_find in gstplayer.o
  "_gst_player_media_info_get_type", referenced from:
      _gst_player_class_init in gstplayer.o
  "_gst_player_media_info_new", referenced from:
      _gst_player_media_info_create in gstplayer.o
  "_gst_player_stream_info_copy", referenced from:
      _gst_player_stream_info_get_current in gstplayer.o
  "_gst_player_stream_info_get_caps", referenced from:
      _stream_info_get_codec in gstplayer.o
  "_gst_player_stream_info_get_index", referenced from:
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _gst_player_subtitle_info_update in gstplayer.o
  "_gst_player_stream_info_get_stream_type", referenced from:
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _gst_player_streams_info_create in gstplayer.o
  "_gst_player_stream_info_get_tags", referenced from:
      _stream_info_get_codec in gstplayer.o
      _get_from_tags in gstplayer.o
  "_gst_player_stream_info_new", referenced from:
      _gst_player_streams_info_create in gstplayer.o
  "_gst_player_subtitle_info_get_type", referenced from:
      _gst_player_get_current_subtitle_track in gstplayer.o
      _gst_player_set_subtitle_track in gstplayer.o
      _gst_player_class_init in gstplayer.o
      _subtitle_changed_cb in gstplayer.o
      _subtitle_tags_changed_cb in gstplayer.o
      _gst_player_media_info_create in gstplayer.o
  "_gst_player_video_info_get_type", referenced from:
      _gst_player_get_current_video_track in gstplayer.o
      _gst_player_set_video_track in gstplayer.o
      _gst_player_class_init in gstplayer.o
      _video_changed_cb in gstplayer.o
      _video_tags_changed_cb in gstplayer.o
      _gst_player_stream_info_update_tags_and_caps in gstplayer.o
      _get_caps in gstplayer.o
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

By the way, I can build and run the iOS example at this link:
http://cgit.freedesktop.org/~slomo/gst-sdk-tutorials/

Any help would be appreciated.

**Comment by sdroege** [comment]
Thanks for reporting. You will probably have to add some new files from lib/gst/player to the iOS project. I don't have a Mac with me currently, so please try that and then send a pull request. Thanks :)

**Comment by TrungDoan** [comment]
Thanks for your feedback. It works now. I just added all files in lib/gst/player to the iOS project. 
But it occurred a new issue. Should i open a new ticket and close this?

**Comment by sdroege** [comment]
Can you send a pull request for the changes you did to the project?
For the other issue, please open another ticket, yes

**Comment by TrungDoan** [comment]
I just created a new pull request related to building issue on iOS.
I will close this issue and open new ticket.
Thanks
