### ISSUE TITLE
[iOS] Video Screen always display black when playing

### ISSUE THREAD

**Issue by TrungDoan** [sdroege/gst-player#84]
Hi,
I could run iOS example successfully. But the Video Screen always display black. The seek position still increase normally. 

Testing Environment:
- iPhone 5 (iOS 8), 6 (iOS 8.4)
- iPhone Simulator 5 (iOS 8.4), 6(iOS 8.4)

Here the log:
(<unknown>:906): GLib-GObject-WARNING **: g_object_set_valist: object class 'GstPlayer' has no property named 'window-handle'

I believe that the GstPlayer is missing some components. Is that right?

I attached images to show the issue.
<img width="376" alt="screen shot 2015-08-18 at 4 57 36 pm" src="https://cloud.githubusercontent.com/assets/978171/9327350/4b07f9c6-45ca-11e5-8894-177432ea665e.png">
<img width="376" alt="screen shot 2015-08-18 at 4 57 06 pm" src="https://cloud.githubusercontent.com/assets/978171/9327351/4b5067f6-45ca-11e5-9241-3e7e831ae78f.png">

Thanks

**Comment by sdroege** [comment]
Yes, I'll push a fix (also for Android) in a bit

**Comment by sdroege** [comment]
Should be fixed by 29c5e5dfaaaa568c2715e397edf32924cdad893b and 5ddeb762ecce20485221dd867f850c5c44aad46c
