### ISSUE TITLE
[iOS] "Too Many File Open" Issue

### ISSUE THREAD

**Issue by TrungDoan** [sdroege/gst-player#85]
Hi,
When i tried to see how long GstPlayer can be used, i saw it throw an error log like this at exactly 40th play:
(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_read_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_read_control: assertion 'set != NULL' failed

(<unknown>:6583): GStreamer-CRITICAL **: gst_poll_free: assertion 'set != NULL' failed

if i ignored the error, i saw new error log at 41st play:
(<unknown>:6583): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

then app crashed.
I experienced the same behavior on iOS Example at this link: http://cgit.freedesktop.org/~slomo/gst-sdk-tutorials/

I assume that gst_object_unref (player) didn't clear all the resources, specifically closing files.

**Comment by sdroege** [comment]
That would be a bug in GStreamer, can you report it at https://bugzilla.gnome.org against GStreamer?

**Comment by TrungDoan** [comment]
Thanks
I reported it.
