### ISSUE TITLE
Make it possible to add text subtitles

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#86]
Rather than having a suburi, applications would add all relevant text subtitles to GstPlayer for that URI to play, and they would be selectable as if they were part of the stream itself.

This would allow adding multiple text subtitles (for example, subtitles in multiple languages), and for users to select which one of them they prefer.

**Comment by codomania** [comment]
I was planning to take a stab and here is what i have in mind and see if you it make sense.

Currently we have gst_player_set_subtitle_uri() this function loads the external subtitle. The external subtitle is loaded during playback. I am proposing to add a new function "gst_player_add_subtitle_uri()" - this function will add the suburi in a GList and possibly create a subtitle streaminfo object for it. But will not load the suburi in playbin and loading still need to be done via gst_player_set_subtitle_uri().

From app i am thinking of the below usage.

player = gst_player_new();
g_object_set(player, "uri", URI, NULL);
gst_player_add_subtitle(player, SUBURI1);
gst_player_add_subtitle(player, SUBURI2);
gst_player_add_subtitle(player, SUBURI3);
gst_player_play(player).

App can use gst_player_set_subtitle_uri(play, SUBURI1) to load the SUBURI1 at run time.

**Comment by sdroege** [comment]
I think this should work a bit different API-wise. Basically you would have a property to set the main uri (what is now the URI property), plus another property (that takes a G_TYPE_STRV of uris) for subtitles.

Internally we would for now handle this by implementing a custom source bin with multiple source elements (one for each suburi) that is then used for the suburi property of playbin. That way we would see all subtitle streams in playbin and have them selectable as usual.

In a later version, this feature should move to playbin/decodebin (which is already somewhere in the plans).

**Comment by codomania** [comment]
Okay got it, I was basically thinking that gst_player_add_subtitle(player, SUBURI1); will simply create a new Subtitle StreamInfo object and add it into current media_info object so that player thinks that added Subtitle is part of stream itself. And normal flow will of stream selection and retrieval will work. Do you see any issue with this approach ? If that sounds a good start then of course instead of creating a API we can use suburis property to get the list of suburis. Only thing which we will need to take care is that since media_info object is first created during READY->PAUSED and user will send suburi-list before pipeline is playing hence we may need to add streaminfo in temporary list and add them once real media_info object is created. does that make sense ?

**Comment by sdroege** [comment]
The way I described it you will automatically get the subtitle stream infos as part of the normal playbin machinery :) You would have all subtitle streams from the suburi of playbin and can switch between them.

To make that work you would have a bin with a custom GstURIHandler (e.g. gst-player-subtitles://0x12345678 where that number is a pointer to the subtitle list), and would then create file sources for each of these.

**Comment by codomania** [comment]
pardon my stupid questions, let me understand your this message a bit more.

_Internally we would for now handle this by implementing a custom source bin with multiple source elements (one for each suburi) that is then used for the suburi property of playbin. That way we would see all subtitle streams in playbin and have them selectable as usual._

I thought suburi property in playbin is "gchar*" which means suburi property will accept a real uri and not the element or bin. Does passing the name of bin in suburi property will work ? Or we need to do something in source-setup signal but i think that's after source element is created.

**Comment by sdroege** [comment]
It's not a stupid question :) The idea is that we would have a GstBin subclass for which we register an element factory (gst_element_register()) with a high enough rank. This GstBin subclass would implement a custom URI scheme (with the GstURIHandler interface). For example it could accept something like "gst-player-subtitles://0x1234578". We would then set this as suburi on playbin, which would then create an instance of our bin, set the URI on it (which then gives us the pointer to our subtitles data structure), and then we would create sources for each subtitle inside this bin to have playbin use them.

**Comment by codomania** [comment]
okay i think i understood a bit more. Let me give a try and i am sure will have lot of more question ;) since i have never created gstbin so it will be  a learning path. if u know of any good reference code to do the above then let pls point me at it.

**Comment by sdroege** [comment]
You could take a look at splitmuxsrc from gst-plugins-good/gst/multifile. It's much more complicated than what is needed here, but it's also a GstBin subclass that implements GstURIHandler and acts as a source with internal source elements.

**Comment by codomania** [comment]
great thanks !

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer&component=gst-plugins-bad

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765305
