### ISSUE TITLE
Add streaming/download streaming support

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#89]
Totem's BaconVideoWidget handles that in:
https://git.gnome.org/browse/totem/tree/src/backend/bacon-video-widget.c#n2209
bvw_handle_buffering_message() and bvw_download_buffering_done()

The playback state and fill-rate should take into account whether enough data has been downloaded to start playback without a pause until the end of the stream (fill level in the seekbar), the current buffering state for live streams (usually a spinner or filling circle), whether one can seek further than the fill-level, and the name of the on-disk copy when download-buffering is done so that the file can be saved to the user's library.

Another feature of the iOS player widget is that the playback button (play/pause) doesn't always reflect the state of the actual playback. When starting a stream, the main button will show a "pause" icon even though the state will be paused/buffering, and clicking on it twice in a short period of time will start playback even if not buffered enough.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765308
