### ISSUE TITLE
Handle rotation

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#90]
In totem, users can either rotate videos by 90 degrees manually, or the rotation is detected through the GST_TAG_IMAGE_ORIENTATION tag.

This needs to handle screen and video aspect ratio changing when rotating the video. Totem's change of rotation is also animated when done manually, which would be nice to have.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765309
