### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#93]
Totem's video widget is full of special casing to make GStreamer's error message human-readable, explanatory, and translated.
https://git.gnome.org/browse/totem/tree/src/backend/bacon-video-widget.c#n3733
bvw_error_from_gst_error()

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=756806

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765311
