### ISSUE TITLE
Handle asking for password/username

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#94]
For HTTP/RTSP and gvfs supported schemes, GstPlayer should know how to ask for the information necessary to show a password dialogue.

See:
https://git.gnome.org/browse/totem/tree/src/backend/bacon-video-widget.c#n1904
bvw_check_missing_auth()

and
https://git.gnome.org/browse/totem/tree/src/backend/bacon-video-widget.c#n1637
bvw_handle_element_message() and mount_cb()

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765312
