### ISSUE TITLE
Add playback speed setting

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#97]
> x1 playback is used for listening to spoken words (Podcasts, lectures, presentations).

**Comment by sdroege** [comment]
That already exists: gst_player_set/get_rate()

**Comment by hadess** [comment]
Which doesn't preserve tempo, does it?

**Comment by sdroege** [comment]
You mean the audio pitch? It doesn't, good point :)

**Comment by sdroege** [comment]
This is done now
